version: '3.8'

services:
  user-service:
    image: usercontroller:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  registration-service:
    image: registrationservice:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

  notification-service:
    image: notificationservice:latest
    ports:
      - "8082:8082"
    networks:
        - my_network

networks:
  my_network:
    driver: bridge

